baseURL = 'http://tl.neocities.org/'
languageCode = 'en-us'
title = 'tl'

[permalinks]
  posts = '/:year/:month/:title/'
  links = '/links/:year/:month/:day/:title/'
  tools = '/tools/:title/'
  pages = '/:title'

[markup.goldmark]
  extensions.typographer.disable = true
  renderer.unsafe = true
      